name: Python Streamlit CI

on:
  push:
    branches: [ homologacao, producao ]
  pull_request:
    branches: [ homologacao, producao ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit psycopg2-binary validate-docbr

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

    - name: Run Streamlit tests
      run: |
        echo "Aqui você pode rodar testes automatizados se existirem"
